-- TODO print warnings if pcall fails

require("fg8r.options")
require("fg8r.keymaps")
require("fg8r.plugins")
require("fg8r.colorscheme")
require("fg8r.cmp")
require("fg8r.lsp")
require("fg8r.telescope")
require("fg8r.treesitter")
require("fg8r.autopairs")
require("fg8r.comment")
require("fg8r.gitsigns")
require("fg8r.nvim-tree")
require("fg8r.lualine")
require("fg8r.bufferline")
require("fg8r.dap")
require("fg8r.autocommands")
